### PR TITLE
Use a conditional import for Hashable for compatibility with Python >= 3.10

### LINKED ISSUE #66: "Hashable" class change for Python 3.10+
If using Python 3.10, we get the following error: ```ImportError: cannot import name 'Hashable' from 'collections'```.

I found the solution [here](https://bobbyhadz.com/blog/python-importerror-cannot-import-name-hashable-from-collections). We just need to modify line 6 of `carta/validation.py` from:

> from collections import Hashable

to

> from collections.abc import Hashable

### PR DESCRIPTION
**Pull request by confluence**
Fixes #66.

### CODE REVIEW

**Review by ajm-ska — APPROVED** [review]
I confirm that this works on Python 3.10.
